security:
  user:
    name: admin
    password: admin
    role: USER
  oauth2:
    client:
      client-id: adminclient
      client-secret: adminsecret
      scope: read,write
      auto-approve-scopes: '.*'