server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product
---
spring:
  profiles: dev-postgres
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/product_service_dataservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
flyway:
  clean-on-validation-error: true
server:
  port: 8088
---
spring:
  profiles: cloud